### ISSUE TITLE
Implement a 2 week limit for past events

### ISSUE THREAD

**Issue by ben-pr-p** [ben-pr-p/esm#1]
This should reduce load time, decrease time to switch between tabs, etc.

**Comment by jinding** [comment]
To flesh this out a little more, this should include:
* Not loading events more than 2 weeks in the past
* Removing the "Past" and "Needs debrief" tabs (we don't use them)
* Removing past events and the label for past events from the Organizer (ie Host) view

**Comment by ben-pr-p** [comment]
Ah, ok – if we want to remove the Past and Needs debrief tabs, then we can just not load events that are in the past at all, right?

**Comment by jinding** [comment]
Doh! You're right. Actually let's just keep the Needs debrief tab then for those in the past 2 weeks.

I think it's good to allow some past events so that hosts can pull RSVPs of recent events.

**Comment by jinding** [comment]
this is done, right?

**Comment by ben-pr-p** [comment]
Yep!
