### ISSUE TITLE
Various sync issues

### ISSUE THREAD

**Issue by jinding** [ben-pr-p/esm#5]
It looks like we're having a number of situations where it seems like ESM may not be reflecting what is current in BSD / visible to RSVPers, and/or changes made in ESM aren't holding:

1. "I checked ESM about 30 minutes ago and it said 73 events were in the needs approval tab. I checked about 3 minutes ago, and it said 63 events were in needs approval. Something seemed fishy and I refreshed again, and then it said 46 events needs approval. I just took a quicktime screenshot video for proof of it saying 46 events, and after clicking refresh, it suddenly saying 73. Something is clearly wrong with reporting on these tabs. What does this mean for the actual approval status of events and auto-emails?"

2. We’re experiencing a ton of lag in the tool. For example, we approved this event at 5:55 PM CT last night (as noted in the edit log on ESM): https://secure.betofortexas.com/page/event/detail/canvass/4jlsy <-- but by 8:50PM CT, it was still in the needs approvals tab. Do you think this is a result of too many events being in the tool?

3. Edits we make aren’t actually saving in ESM. We changed the title of this event to “phonebank for beto | tyler” and saved it, but “Phone Bank for Beto: Foundry Coffee House” is continuing to stay  in ESM. You can see in the edit log history we made that change at 6:37 PM, and it’s still not making these changes in ESM, but the correct title is on the actual event map link: https://secure.betofortexas.com/page/event/detail/phonebank/4jl9k

Could you dig in to why these are happening, and also let us know "how is all of this lag, potential double/triple/4x approving events because we can’t keep track of ones that were actually approved, and edits not actually sticking affecting the auto-emails that hosts are receiving?"

**Comment by jinding** [comment]
i believe the sync is off, correct?

**Comment by ben-pr-p** [comment]
The sync is now, off, yes. I have left the caching layer up on https://github.com/justicedemocrats/osdi-proxy to keep load time down, but the logic over there is much simpler 💯
